language: php

dist: trusty
sudo: false

git:
    depth: 1

php:
#    - 7.0
    - 7.1
    - 7.2
    - 7.3

cache:
    directories:
        - $HOME/.composer/cache/files
        - .phpunit

env:
    global:
        - SYMFONY_PHPUNIT_DIR=.phpunit

install:
    - composer --prefer-dist install
    - ./vendor/bin/simple-phpunit install
#    - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
#    - chmod +x coveralls.phar
#    - php coveralls.phar --version


script: ./vendor/bin/simple-phpunit

#after_success:
#    - php coveralls.phar -v